 ~/.p10k.zsh — Powerlevel10k Configuration
# Generated by translating your Oh My Posh theme into Powerlevel10k
# Place this file at ~/.p10k.zsh and ensure your ~/.zshrc sources it below the theme.

# ----------------------------------------------------------------------------
# Prompt Segments Order
# ----------------------------------------------------------------------------
# Left prompt: time, kubectl context, aws profile, git status, background jobs
# Right prompt: exit status
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                  # exit code of the last command
    time
  )

# Left prompt segments
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  context
  timewarrior
  taskwarrior
  dir
  os_icon
  vcs
  # Add other segments as desired
)

# Right prompt segments
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  time
  # Add other segments as desired
)

typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

# ----------------------------------------------------------------------------
# General Settings
# ----------------------------------------------------------------------------
# Use Nerd Font symbols and Powerline separators
typeset -g POWERLEVEL9K_MODE='nerdfont-complete'
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_ICON_PADDING=none

# ----------------------------------------------------------------------------
# Segment Configurations
# ----------------------------------------------------------------------------

# Foreground and background colors
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#75B5AA'
typeset -g POWERLEVEL9K_DIR_BACKGROUND='#000000'

# Icons
typeset -g POWERLEVEL9K_DIR_ICON=''

# Styles (bold, underline, etc.)
typeset -g POWERLEVEL9K_DIR_STYLE='bold'

typeset -g POWERLEVEL9K_USER_FOREGROUND='#75B5AA'
typeset -g POWERLEVEL9K_HOST_FOREGROUND='#75B5AA'


typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%I:%M:%S %p}'
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#75B5AA'
typeset -g POWERLEVEL9K_TIME_BACKGROUND='#000000'

# Kubectl segment: Kubernetes context and namespace
typeset -g POWERLEVEL9K_KUBECTL_FOREGROUND='#FFBB00'
typeset -g POWERLEVEL9K_KUBECTL_ICON=''

# AWS segment: profile and region display
typeset -g POWERLEVEL9K_AWS_FOREGROUND='#4285F4'

# Git segment: repo status, branch, changes
typeset -g POWERLEVEL9K_GIT_FOREGROUND='#238636'

# Background jobs segment: show count only
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='#75B5AA'

# Execution time segment: show if >1ms
typeset -g POWERLEVEL9K_EXECUTION_TIME_THRESHOLD=1
typeset -g POWERLEVEL9K_EXECUTION_TIME_FOREGROUND='#75B5AA'

# Status segment: different colors for OK vs error
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='#75B5AA'
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND='#DD0033'

# Os Icon Stuff
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='#75B5AA'

# Context stuff
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=1
typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=0

typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=3
typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=0

typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE='%n@%m'
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'


###[ virtualenv: python virtual environment (https://docs.python.org/3/library/venv.html) ]###
# Python virtual environment color.
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=0
typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=4
# Don't show Python version next to the virtual environment name.
typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
# If set to "false", won't show virtualenv if pyenv is already shown.
# If set to "if-different", won't show virtualenv if it's the same as pyenv.
typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=false
# Separate environment name from Python version only with a space.
typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=
# Custom icon.
# typeset -g POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION='⭐'

# ----------------------------------------------------------------------------
# End of ~/.p10k.zsh
# Reload your shell or run `p10k reload` after making changes.
# ----------------------------------------------------------------------------